MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/user/runs/vltrain/121/model_0040000.pth"
  BACKBONE_PREFIX: "backbone.body."
  LOAD_EMB_PRED_FROM_MMSS_HEAD: True
  LOAD_TRAINER_STATE: False
  CLS_AGNOSTIC_BBOX_REG: True
  ROI_BOX_HEAD:
    # Note these are the number of classes for training only
    NUM_CLASSES: 81
    EMB_DIM: 768
    EMBEDDING_BASED: True
    LOSS_WEIGHT_BACKGROUND: 0.2
    FREEZE_EMB_PRED: True
  ROI_HEADS:
    POSITIVE_FRACTION: 1.0
  BACKBONE:
    FREEZE_CONV_BODY_AT: 2
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  DATASET_CLASS: "COCODataset"
  DATASET_ARGS: 
    LOAD_EMBEDDINGS: True
    EMB_KEY: "BertEmb"
    EMB_DIM: 768
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 120000)
  MAX_ITER: 150000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 10000
  TEST_PERIOD: 10000
  LOG_PERIOD: 100
TEST:
  IMS_PER_BATCH: 8
